//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedadLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutochargeContentsSendedToUser
    {
        public long Id { get; set; }
        public long SubscriberId { get; set; }
        public long AutochargeContentId { get; set; }
        public System.DateTime DateAdded { get; set; }
    }
}
