//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageArchive
    {
        public long Id { get; set; }
        public string MobileNumber { get; set; }
        public string Content { get; set; }
        public Nullable<int> ProcessStatus { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public string ReferenceId { get; set; }
        public Nullable<int> TimesTryingToSend { get; set; }
        public Nullable<int> MessageType { get; set; }
        public Nullable<long> ServiceId { get; set; }
        public Nullable<long> SubscriberId { get; set; }
        public Nullable<long> ContentId { get; set; }
        public Nullable<int> ImiChargeCode { get; set; }
        public Nullable<int> ImiMessageType { get; set; }
        public string DeliveryStatus { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> OperatorId { get; set; }
        public Nullable<System.DateTime> DateAddedToQueue { get; set; }
        public Nullable<int> AggregatorServiceId { get; set; }
    }
}
