//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mo
    {
        public long Id { get; set; }
        public string MobileNumber { get; set; }
        public string ShortCode { get; set; }
        public System.DateTime ReceivedTime { get; set; }
        public string MessageId { get; set; }
    }
}
