//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortalEntities : DbContext
    {
        public PortalEntities()
            : base("name=PortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MessageArchive> MessageArchives { get; set; }
        public virtual DbSet<MessageBuffer> MessageBuffers { get; set; }
        public virtual DbSet<Mo> Moes { get; set; }
        public virtual DbSet<OperatorsList> OperatorsLists { get; set; }
        public virtual DbSet<OperatorsPlan> OperatorsPlans { get; set; }
        public virtual DbSet<OperatorsPrefix> OperatorsPrefixs { get; set; }
        public virtual DbSet<OperatorsRecharageCode> OperatorsRecharageCodes { get; set; }
        public virtual DbSet<RPS_ServiceAdditionalInfo> RPS_ServiceAdditionalInfo { get; set; }
        public virtual DbSet<ServiceShortCode> ServiceShortCodes { get; set; }
        public virtual DbSet<Subscriber> Subscribers { get; set; }
        public virtual DbSet<SubscribersHistory> SubscribersHistories { get; set; }
        public virtual DbSet<AggregatorList> AggregatorLists { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<RPS_SubscribersAdditionalInfo> RPS_SubscribersAdditionalInfo { get; set; }
    }
}
