//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedLibrary.MciSendUssdServiceServiceReference {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
    public partial class PolicyException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageIdField;
        
        private string textField;
        
        private string[] variablesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("messageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("variables", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string[] variables {
            get {
                return this.variablesField;
            }
            set {
                this.variablesField = value;
                this.RaisePropertyChanged("variables");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/ussd/v4_0")]
    public partial class Status : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/ussd/send/v4_0/local")]
    public partial class beginUssdResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Status resultField;
        
        private string sessionIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Status result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("SessionID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/ussd/send/v4_0/local")]
    public partial class beginUssd : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceKeyField;
        
        private string addressField;
        
        private string messageField;
        
        private string dCSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ServiceKey {
            get {
                return this.serviceKeyField;
            }
            set {
                this.serviceKeyField = value;
                this.RaisePropertyChanged("ServiceKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=1)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DCS {
            get {
                return this.dCSField;
            }
            set {
                this.dCSField = value;
                this.RaisePropertyChanged("DCS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
    public partial class ServiceException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageIdField;
        
        private string textField;
        
        private string[] variablesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("messageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("variables", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string[] variables {
            get {
                return this.variablesField;
            }
            set {
                this.variablesField = value;
                this.RaisePropertyChanged("variables");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.csapi.org/wsdl/parlayx/ussd/send/v4_0/interface", ConfigurationName="MciSendUssdServiceServiceReference.SendUssd")]
    public interface SendUssd {
        
        // CODEGEN: Generating message contract since the operation beginUssd is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csapi.org/wsdl/parlayx/ussd/send/v4_0/interface/SendUssd/beginUssdRequ" +
            "est", ReplyAction="http://www.csapi.org/wsdl/parlayx/ussd/send/v4_0/interface/SendUssd/beginUssdResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SharedLibrary.MciSendUssdServiceServiceReference.PolicyException), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="PolicyException", Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
        [System.ServiceModel.FaultContractAttribute(typeof(SharedLibrary.MciSendUssdServiceServiceReference.ServiceException), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="ServiceException", Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SharedLibrary.MciSendUssdServiceServiceReference.beginUssdResponse1 beginUssd(SharedLibrary.MciSendUssdServiceServiceReference.beginUssdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csapi.org/wsdl/parlayx/ussd/send/v4_0/interface/SendUssd/beginUssdRequ" +
            "est", ReplyAction="http://www.csapi.org/wsdl/parlayx/ussd/send/v4_0/interface/SendUssd/beginUssdResp" +
            "onse")]
        System.Threading.Tasks.Task<SharedLibrary.MciSendUssdServiceServiceReference.beginUssdResponse1> beginUssdAsync(SharedLibrary.MciSendUssdServiceServiceReference.beginUssdRequest request);
        
        // CODEGEN: Generating message contract since the operation continueUssd is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csapi.org/wsdl/parlayx/ussd/send/v4_0/interface/SendUssd/continueUssdR" +
            "equest", ReplyAction="http://www.csapi.org/wsdl/parlayx/ussd/send/v4_0/interface/SendUssd/continueUssdR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SharedLibrary.MciSendUssdServiceServiceReference.PolicyException), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="PolicyException", Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
        [System.ServiceModel.FaultContractAttribute(typeof(SharedLibrary.MciSendUssdServiceServiceReference.ServiceException), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="ServiceException", Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SharedLibrary.MciSendUssdServiceServiceReference.continueUssdResponse1 continueUssd(SharedLibrary.MciSendUssdServiceServiceReference.continueUssdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csapi.org/wsdl/parlayx/ussd/send/v4_0/interface/SendUssd/continueUssdR" +
            "equest", ReplyAction="http://www.csapi.org/wsdl/parlayx/ussd/send/v4_0/interface/SendUssd/continueUssdR" +
            "esponse")]
        System.Threading.Tasks.Task<SharedLibrary.MciSendUssdServiceServiceReference.continueUssdResponse1> continueUssdAsync(SharedLibrary.MciSendUssdServiceServiceReference.continueUssdRequest request);
        
        // CODEGEN: Generating message contract since the operation endUssd is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csapi.org/wsdl/parlayx/ussd/send/v4_0/interface/SendUssd/endUssdReques" +
            "t", ReplyAction="http://www.csapi.org/wsdl/parlayx/ussd/send/v4_0/interface/SendUssd/endUssdRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(SharedLibrary.MciSendUssdServiceServiceReference.PolicyException), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="PolicyException", Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
        [System.ServiceModel.FaultContractAttribute(typeof(SharedLibrary.MciSendUssdServiceServiceReference.ServiceException), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="ServiceException", Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SharedLibrary.MciSendUssdServiceServiceReference.endUssdResponse1 endUssd(SharedLibrary.MciSendUssdServiceServiceReference.endUssdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csapi.org/wsdl/parlayx/ussd/send/v4_0/interface/SendUssd/endUssdReques" +
            "t", ReplyAction="http://www.csapi.org/wsdl/parlayx/ussd/send/v4_0/interface/SendUssd/endUssdRespon" +
            "se")]
        System.Threading.Tasks.Task<SharedLibrary.MciSendUssdServiceServiceReference.endUssdResponse1> endUssdAsync(SharedLibrary.MciSendUssdServiceServiceReference.endUssdRequest request);
        
        // CODEGEN: Generating message contract since the operation notifyUssd is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csapi.org/wsdl/parlayx/ussd/send/v4_0/interface/SendUssd/notifyUssdReq" +
            "uest", ReplyAction="http://www.csapi.org/wsdl/parlayx/ussd/send/v4_0/interface/SendUssd/notifyUssdRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SharedLibrary.MciSendUssdServiceServiceReference.PolicyException), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="PolicyException", Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
        [System.ServiceModel.FaultContractAttribute(typeof(SharedLibrary.MciSendUssdServiceServiceReference.ServiceException), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="ServiceException", Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SharedLibrary.MciSendUssdServiceServiceReference.notifyUssdResponse1 notifyUssd(SharedLibrary.MciSendUssdServiceServiceReference.notifyUssdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csapi.org/wsdl/parlayx/ussd/send/v4_0/interface/SendUssd/notifyUssdReq" +
            "uest", ReplyAction="http://www.csapi.org/wsdl/parlayx/ussd/send/v4_0/interface/SendUssd/notifyUssdRes" +
            "ponse")]
        System.Threading.Tasks.Task<SharedLibrary.MciSendUssdServiceServiceReference.notifyUssdResponse1> notifyUssdAsync(SharedLibrary.MciSendUssdServiceServiceReference.notifyUssdRequest request);
        
        // CODEGEN: Generating message contract since the operation abortUssd is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csapi.org/wsdl/parlayx/ussd/send/v4_0/interface/SendUssd/abortUssdRequ" +
            "est", ReplyAction="http://www.csapi.org/wsdl/parlayx/ussd/send/v4_0/interface/SendUssd/abortUssdResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SharedLibrary.MciSendUssdServiceServiceReference.PolicyException), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="PolicyException", Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
        [System.ServiceModel.FaultContractAttribute(typeof(SharedLibrary.MciSendUssdServiceServiceReference.ServiceException), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="ServiceException", Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SharedLibrary.MciSendUssdServiceServiceReference.abortUssdResponse1 abortUssd(SharedLibrary.MciSendUssdServiceServiceReference.abortUssdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csapi.org/wsdl/parlayx/ussd/send/v4_0/interface/SendUssd/abortUssdRequ" +
            "est", ReplyAction="http://www.csapi.org/wsdl/parlayx/ussd/send/v4_0/interface/SendUssd/abortUssdResp" +
            "onse")]
        System.Threading.Tasks.Task<SharedLibrary.MciSendUssdServiceServiceReference.abortUssdResponse1> abortUssdAsync(SharedLibrary.MciSendUssdServiceServiceReference.abortUssdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class beginUssdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.csapi.org/schema/parlayx/ussd/send/v4_0/local", Order=0)]
        public SharedLibrary.MciSendUssdServiceServiceReference.beginUssd beginUssd;
        
        public beginUssdRequest() {
        }
        
        public beginUssdRequest(SharedLibrary.MciSendUssdServiceServiceReference.beginUssd beginUssd) {
            this.beginUssd = beginUssd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class beginUssdResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.csapi.org/schema/parlayx/ussd/send/v4_0/local", Order=0)]
        public SharedLibrary.MciSendUssdServiceServiceReference.beginUssdResponse beginUssdResponse;
        
        public beginUssdResponse1() {
        }
        
        public beginUssdResponse1(SharedLibrary.MciSendUssdServiceServiceReference.beginUssdResponse beginUssdResponse) {
            this.beginUssdResponse = beginUssdResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/ussd/send/v4_0/local")]
    public partial class continueUssd : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceKeyField;
        
        private string sessionIDField;
        
        private string addressField;
        
        private string messageField;
        
        private string dCSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ServiceKey {
            get {
                return this.serviceKeyField;
            }
            set {
                this.serviceKeyField = value;
                this.RaisePropertyChanged("ServiceKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("SessionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=2)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DCS {
            get {
                return this.dCSField;
            }
            set {
                this.dCSField = value;
                this.RaisePropertyChanged("DCS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/ussd/send/v4_0/local")]
    public partial class continueUssdResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Status resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Status result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class continueUssdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.csapi.org/schema/parlayx/ussd/send/v4_0/local", Order=0)]
        public SharedLibrary.MciSendUssdServiceServiceReference.continueUssd continueUssd;
        
        public continueUssdRequest() {
        }
        
        public continueUssdRequest(SharedLibrary.MciSendUssdServiceServiceReference.continueUssd continueUssd) {
            this.continueUssd = continueUssd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class continueUssdResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.csapi.org/schema/parlayx/ussd/send/v4_0/local", Order=0)]
        public SharedLibrary.MciSendUssdServiceServiceReference.continueUssdResponse continueUssdResponse;
        
        public continueUssdResponse1() {
        }
        
        public continueUssdResponse1(SharedLibrary.MciSendUssdServiceServiceReference.continueUssdResponse continueUssdResponse) {
            this.continueUssdResponse = continueUssdResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/ussd/send/v4_0/local")]
    public partial class endUssd : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceKeyField;
        
        private string sessionIDField;
        
        private string addressField;
        
        private string messageField;
        
        private string dCSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ServiceKey {
            get {
                return this.serviceKeyField;
            }
            set {
                this.serviceKeyField = value;
                this.RaisePropertyChanged("ServiceKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("SessionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=2)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DCS {
            get {
                return this.dCSField;
            }
            set {
                this.dCSField = value;
                this.RaisePropertyChanged("DCS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/ussd/send/v4_0/local")]
    public partial class endUssdResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Status resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Status result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class endUssdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.csapi.org/schema/parlayx/ussd/send/v4_0/local", Order=0)]
        public SharedLibrary.MciSendUssdServiceServiceReference.endUssd endUssd;
        
        public endUssdRequest() {
        }
        
        public endUssdRequest(SharedLibrary.MciSendUssdServiceServiceReference.endUssd endUssd) {
            this.endUssd = endUssd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class endUssdResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.csapi.org/schema/parlayx/ussd/send/v4_0/local", Order=0)]
        public SharedLibrary.MciSendUssdServiceServiceReference.endUssdResponse endUssdResponse;
        
        public endUssdResponse1() {
        }
        
        public endUssdResponse1(SharedLibrary.MciSendUssdServiceServiceReference.endUssdResponse endUssdResponse) {
            this.endUssdResponse = endUssdResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/ussd/send/v4_0/local")]
    public partial class notifyUssd : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceKeyField;
        
        private string addressField;
        
        private string messageField;
        
        private string dCSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ServiceKey {
            get {
                return this.serviceKeyField;
            }
            set {
                this.serviceKeyField = value;
                this.RaisePropertyChanged("ServiceKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=1)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DCS {
            get {
                return this.dCSField;
            }
            set {
                this.dCSField = value;
                this.RaisePropertyChanged("DCS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/ussd/send/v4_0/local")]
    public partial class notifyUssdResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Status resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Status result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class notifyUssdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.csapi.org/schema/parlayx/ussd/send/v4_0/local", Order=0)]
        public SharedLibrary.MciSendUssdServiceServiceReference.notifyUssd notifyUssd;
        
        public notifyUssdRequest() {
        }
        
        public notifyUssdRequest(SharedLibrary.MciSendUssdServiceServiceReference.notifyUssd notifyUssd) {
            this.notifyUssd = notifyUssd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class notifyUssdResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.csapi.org/schema/parlayx/ussd/send/v4_0/local", Order=0)]
        public SharedLibrary.MciSendUssdServiceServiceReference.notifyUssdResponse notifyUssdResponse;
        
        public notifyUssdResponse1() {
        }
        
        public notifyUssdResponse1(SharedLibrary.MciSendUssdServiceServiceReference.notifyUssdResponse notifyUssdResponse) {
            this.notifyUssdResponse = notifyUssdResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/ussd/send/v4_0/local")]
    public partial class abortUssd : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceKeyField;
        
        private string addressField;
        
        private string sessionIDField;
        
        private Reason abortReasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ServiceKey {
            get {
                return this.serviceKeyField;
            }
            set {
                this.serviceKeyField = value;
                this.RaisePropertyChanged("ServiceKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=1)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("SessionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Reason AbortReason {
            get {
                return this.abortReasonField;
            }
            set {
                this.abortReasonField = value;
                this.RaisePropertyChanged("AbortReason");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/ussd/v4_0")]
    public partial class Reason : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/ussd/send/v4_0/local")]
    public partial class abortUssdResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Status resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Status result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class abortUssdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.csapi.org/schema/parlayx/ussd/send/v4_0/local", Order=0)]
        public SharedLibrary.MciSendUssdServiceServiceReference.abortUssd abortUssd;
        
        public abortUssdRequest() {
        }
        
        public abortUssdRequest(SharedLibrary.MciSendUssdServiceServiceReference.abortUssd abortUssd) {
            this.abortUssd = abortUssd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class abortUssdResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.csapi.org/schema/parlayx/ussd/send/v4_0/local", Order=0)]
        public SharedLibrary.MciSendUssdServiceServiceReference.abortUssdResponse abortUssdResponse;
        
        public abortUssdResponse1() {
        }
        
        public abortUssdResponse1(SharedLibrary.MciSendUssdServiceServiceReference.abortUssdResponse abortUssdResponse) {
            this.abortUssdResponse = abortUssdResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendUssdChannel : SharedLibrary.MciSendUssdServiceServiceReference.SendUssd, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendUssdClient : System.ServiceModel.ClientBase<SharedLibrary.MciSendUssdServiceServiceReference.SendUssd>, SharedLibrary.MciSendUssdServiceServiceReference.SendUssd {
        
        public SendUssdClient() {
        }
        
        public SendUssdClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendUssdClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendUssdClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendUssdClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharedLibrary.MciSendUssdServiceServiceReference.beginUssdResponse1 SharedLibrary.MciSendUssdServiceServiceReference.SendUssd.beginUssd(SharedLibrary.MciSendUssdServiceServiceReference.beginUssdRequest request) {
            return base.Channel.beginUssd(request);
        }
        
        public SharedLibrary.MciSendUssdServiceServiceReference.beginUssdResponse beginUssd(SharedLibrary.MciSendUssdServiceServiceReference.beginUssd beginUssd1) {
            SharedLibrary.MciSendUssdServiceServiceReference.beginUssdRequest inValue = new SharedLibrary.MciSendUssdServiceServiceReference.beginUssdRequest();
            inValue.beginUssd = beginUssd1;
            SharedLibrary.MciSendUssdServiceServiceReference.beginUssdResponse1 retVal = ((SharedLibrary.MciSendUssdServiceServiceReference.SendUssd)(this)).beginUssd(inValue);
            return retVal.beginUssdResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharedLibrary.MciSendUssdServiceServiceReference.beginUssdResponse1> SharedLibrary.MciSendUssdServiceServiceReference.SendUssd.beginUssdAsync(SharedLibrary.MciSendUssdServiceServiceReference.beginUssdRequest request) {
            return base.Channel.beginUssdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharedLibrary.MciSendUssdServiceServiceReference.beginUssdResponse1> beginUssdAsync(SharedLibrary.MciSendUssdServiceServiceReference.beginUssd beginUssd) {
            SharedLibrary.MciSendUssdServiceServiceReference.beginUssdRequest inValue = new SharedLibrary.MciSendUssdServiceServiceReference.beginUssdRequest();
            inValue.beginUssd = beginUssd;
            return ((SharedLibrary.MciSendUssdServiceServiceReference.SendUssd)(this)).beginUssdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharedLibrary.MciSendUssdServiceServiceReference.continueUssdResponse1 SharedLibrary.MciSendUssdServiceServiceReference.SendUssd.continueUssd(SharedLibrary.MciSendUssdServiceServiceReference.continueUssdRequest request) {
            return base.Channel.continueUssd(request);
        }
        
        public SharedLibrary.MciSendUssdServiceServiceReference.continueUssdResponse continueUssd(SharedLibrary.MciSendUssdServiceServiceReference.continueUssd continueUssd1) {
            SharedLibrary.MciSendUssdServiceServiceReference.continueUssdRequest inValue = new SharedLibrary.MciSendUssdServiceServiceReference.continueUssdRequest();
            inValue.continueUssd = continueUssd1;
            SharedLibrary.MciSendUssdServiceServiceReference.continueUssdResponse1 retVal = ((SharedLibrary.MciSendUssdServiceServiceReference.SendUssd)(this)).continueUssd(inValue);
            return retVal.continueUssdResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharedLibrary.MciSendUssdServiceServiceReference.continueUssdResponse1> SharedLibrary.MciSendUssdServiceServiceReference.SendUssd.continueUssdAsync(SharedLibrary.MciSendUssdServiceServiceReference.continueUssdRequest request) {
            return base.Channel.continueUssdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharedLibrary.MciSendUssdServiceServiceReference.continueUssdResponse1> continueUssdAsync(SharedLibrary.MciSendUssdServiceServiceReference.continueUssd continueUssd) {
            SharedLibrary.MciSendUssdServiceServiceReference.continueUssdRequest inValue = new SharedLibrary.MciSendUssdServiceServiceReference.continueUssdRequest();
            inValue.continueUssd = continueUssd;
            return ((SharedLibrary.MciSendUssdServiceServiceReference.SendUssd)(this)).continueUssdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharedLibrary.MciSendUssdServiceServiceReference.endUssdResponse1 SharedLibrary.MciSendUssdServiceServiceReference.SendUssd.endUssd(SharedLibrary.MciSendUssdServiceServiceReference.endUssdRequest request) {
            return base.Channel.endUssd(request);
        }
        
        public SharedLibrary.MciSendUssdServiceServiceReference.endUssdResponse endUssd(SharedLibrary.MciSendUssdServiceServiceReference.endUssd endUssd1) {
            SharedLibrary.MciSendUssdServiceServiceReference.endUssdRequest inValue = new SharedLibrary.MciSendUssdServiceServiceReference.endUssdRequest();
            inValue.endUssd = endUssd1;
            SharedLibrary.MciSendUssdServiceServiceReference.endUssdResponse1 retVal = ((SharedLibrary.MciSendUssdServiceServiceReference.SendUssd)(this)).endUssd(inValue);
            return retVal.endUssdResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharedLibrary.MciSendUssdServiceServiceReference.endUssdResponse1> SharedLibrary.MciSendUssdServiceServiceReference.SendUssd.endUssdAsync(SharedLibrary.MciSendUssdServiceServiceReference.endUssdRequest request) {
            return base.Channel.endUssdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharedLibrary.MciSendUssdServiceServiceReference.endUssdResponse1> endUssdAsync(SharedLibrary.MciSendUssdServiceServiceReference.endUssd endUssd) {
            SharedLibrary.MciSendUssdServiceServiceReference.endUssdRequest inValue = new SharedLibrary.MciSendUssdServiceServiceReference.endUssdRequest();
            inValue.endUssd = endUssd;
            return ((SharedLibrary.MciSendUssdServiceServiceReference.SendUssd)(this)).endUssdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharedLibrary.MciSendUssdServiceServiceReference.notifyUssdResponse1 SharedLibrary.MciSendUssdServiceServiceReference.SendUssd.notifyUssd(SharedLibrary.MciSendUssdServiceServiceReference.notifyUssdRequest request) {
            return base.Channel.notifyUssd(request);
        }
        
        public SharedLibrary.MciSendUssdServiceServiceReference.notifyUssdResponse notifyUssd(SharedLibrary.MciSendUssdServiceServiceReference.notifyUssd notifyUssd1) {
            SharedLibrary.MciSendUssdServiceServiceReference.notifyUssdRequest inValue = new SharedLibrary.MciSendUssdServiceServiceReference.notifyUssdRequest();
            inValue.notifyUssd = notifyUssd1;
            SharedLibrary.MciSendUssdServiceServiceReference.notifyUssdResponse1 retVal = ((SharedLibrary.MciSendUssdServiceServiceReference.SendUssd)(this)).notifyUssd(inValue);
            return retVal.notifyUssdResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharedLibrary.MciSendUssdServiceServiceReference.notifyUssdResponse1> SharedLibrary.MciSendUssdServiceServiceReference.SendUssd.notifyUssdAsync(SharedLibrary.MciSendUssdServiceServiceReference.notifyUssdRequest request) {
            return base.Channel.notifyUssdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharedLibrary.MciSendUssdServiceServiceReference.notifyUssdResponse1> notifyUssdAsync(SharedLibrary.MciSendUssdServiceServiceReference.notifyUssd notifyUssd) {
            SharedLibrary.MciSendUssdServiceServiceReference.notifyUssdRequest inValue = new SharedLibrary.MciSendUssdServiceServiceReference.notifyUssdRequest();
            inValue.notifyUssd = notifyUssd;
            return ((SharedLibrary.MciSendUssdServiceServiceReference.SendUssd)(this)).notifyUssdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharedLibrary.MciSendUssdServiceServiceReference.abortUssdResponse1 SharedLibrary.MciSendUssdServiceServiceReference.SendUssd.abortUssd(SharedLibrary.MciSendUssdServiceServiceReference.abortUssdRequest request) {
            return base.Channel.abortUssd(request);
        }
        
        public SharedLibrary.MciSendUssdServiceServiceReference.abortUssdResponse abortUssd(SharedLibrary.MciSendUssdServiceServiceReference.abortUssd abortUssd1) {
            SharedLibrary.MciSendUssdServiceServiceReference.abortUssdRequest inValue = new SharedLibrary.MciSendUssdServiceServiceReference.abortUssdRequest();
            inValue.abortUssd = abortUssd1;
            SharedLibrary.MciSendUssdServiceServiceReference.abortUssdResponse1 retVal = ((SharedLibrary.MciSendUssdServiceServiceReference.SendUssd)(this)).abortUssd(inValue);
            return retVal.abortUssdResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharedLibrary.MciSendUssdServiceServiceReference.abortUssdResponse1> SharedLibrary.MciSendUssdServiceServiceReference.SendUssd.abortUssdAsync(SharedLibrary.MciSendUssdServiceServiceReference.abortUssdRequest request) {
            return base.Channel.abortUssdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharedLibrary.MciSendUssdServiceServiceReference.abortUssdResponse1> abortUssdAsync(SharedLibrary.MciSendUssdServiceServiceReference.abortUssd abortUssd) {
            SharedLibrary.MciSendUssdServiceServiceReference.abortUssdRequest inValue = new SharedLibrary.MciSendUssdServiceServiceReference.abortUssdRequest();
            inValue.abortUssd = abortUssd;
            return ((SharedLibrary.MciSendUssdServiceServiceReference.SendUssd)(this)).abortUssdAsync(inValue);
        }
    }
}
