//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DehnadNotificationService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSetting
    {
        public long Id { get; set; }
        public long ChatId { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
    }
}
