//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedLibrary.MciSendSmsServiceBulkServiceReference {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
    public partial class PolicyException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageIdField;
        
        private string textField;
        
        private string[] variablesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("messageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("variables", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string[] variables {
            get {
                return this.variablesField;
            }
            set {
                this.variablesField = value;
                this.RaisePropertyChanged("variables");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/send/v4_0/local")]
    public partial class sendSmsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
    public partial class SimpleReference : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string endpointField;
        
        private string interfaceNameField;
        
        private string correlatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=0)]
        public string endpoint {
            get {
                return this.endpointField;
            }
            set {
                this.endpointField = value;
                this.RaisePropertyChanged("endpoint");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string interfaceName {
            get {
                return this.interfaceNameField;
            }
            set {
                this.interfaceNameField = value;
                this.RaisePropertyChanged("interfaceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correlator {
            get {
                return this.correlatorField;
            }
            set {
                this.correlatorField = value;
                this.RaisePropertyChanged("correlator");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
    public partial class ChargingInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] descriptionField;
        
        private string currencyField;
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("description", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string[] description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
                this.RaisePropertyChanged("amountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
    public partial class sendMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] addressesField;
        
        private string senderNameField;
        
        private ChargingInformation chargingField;
        
        private string messageField;
        
        private SimpleReference receiptRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("addresses", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=0)]
        public string[] addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
                this.RaisePropertyChanged("addresses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string senderName {
            get {
                return this.senderNameField;
            }
            set {
                this.senderNameField = value;
                this.RaisePropertyChanged("senderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ChargingInformation charging {
            get {
                return this.chargingField;
            }
            set {
                this.chargingField = value;
                this.RaisePropertyChanged("charging");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public SimpleReference receiptRequest {
            get {
                return this.receiptRequestField;
            }
            set {
                this.receiptRequestField = value;
                this.RaisePropertyChanged("receiptRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
    public partial class ServiceException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageIdField;
        
        private string textField;
        
        private string[] variablesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("messageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("variables", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string[] variables {
            get {
                return this.variablesField;
            }
            set {
                this.variablesField = value;
                this.RaisePropertyChanged("variables");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface", ConfigurationName="MciSendSmsServiceBulkServiceReference.SendSms")]
    public interface SendSms {
        
        // CODEGEN: Generating message contract since the operation sendSms is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/sendSmsRequest", ReplyAction="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/sendSmsResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(SharedLibrary.MciSendSmsServiceBulkServiceReference.PolicyException), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="PolicyException", Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
        [System.ServiceModel.FaultContractAttribute(typeof(SharedLibrary.MciSendSmsServiceBulkServiceReference.ServiceException), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="ServiceException", Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SharedLibrary.MciSendSmsServiceBulkServiceReference.sendSmsResponse1 sendSms(SharedLibrary.MciSendSmsServiceBulkServiceReference.sendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/sendSmsRequest", ReplyAction="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/sendSmsResponse" +
            "")]
        System.Threading.Tasks.Task<SharedLibrary.MciSendSmsServiceBulkServiceReference.sendSmsResponse1> sendSmsAsync(SharedLibrary.MciSendSmsServiceBulkServiceReference.sendSmsRequest request);
        
        // CODEGEN: Generating message contract since the operation sendBinarySms is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/sendBinarySmsRe" +
            "quest", ReplyAction="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/sendBinarySmsRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SharedLibrary.MciSendSmsServiceBulkServiceReference.PolicyException), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="PolicyException", Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
        [System.ServiceModel.FaultContractAttribute(typeof(SharedLibrary.MciSendSmsServiceBulkServiceReference.ServiceException), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="ServiceException", Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SharedLibrary.MciSendSmsServiceBulkServiceReference.sendBinarySmsResponse1 sendBinarySms(SharedLibrary.MciSendSmsServiceBulkServiceReference.sendBinarySmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/sendBinarySmsRe" +
            "quest", ReplyAction="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/sendBinarySmsRe" +
            "sponse")]
        System.Threading.Tasks.Task<SharedLibrary.MciSendSmsServiceBulkServiceReference.sendBinarySmsResponse1> sendBinarySmsAsync(SharedLibrary.MciSendSmsServiceBulkServiceReference.sendBinarySmsRequest request);
        
        // CODEGEN: Generating message contract since the operation getSmsDeliveryStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/getSmsDeliveryS" +
            "tatusRequest", ReplyAction="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/getSmsDeliveryS" +
            "tatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SharedLibrary.MciSendSmsServiceBulkServiceReference.PolicyException), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="PolicyException", Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
        [System.ServiceModel.FaultContractAttribute(typeof(SharedLibrary.MciSendSmsServiceBulkServiceReference.ServiceException), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="ServiceException", Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SharedLibrary.MciSendSmsServiceBulkServiceReference.getSmsDeliveryStatusResponse getSmsDeliveryStatus(SharedLibrary.MciSendSmsServiceBulkServiceReference.getSmsDeliveryStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/getSmsDeliveryS" +
            "tatusRequest", ReplyAction="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/getSmsDeliveryS" +
            "tatusResponse")]
        System.Threading.Tasks.Task<SharedLibrary.MciSendSmsServiceBulkServiceReference.getSmsDeliveryStatusResponse> getSmsDeliveryStatusAsync(SharedLibrary.MciSendSmsServiceBulkServiceReference.getSmsDeliveryStatusRequest request);
        
        // CODEGEN: Generating message contract since the operation scheduleSms is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/scheduleSmsRequ" +
            "est", ReplyAction="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/scheduleSmsResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SharedLibrary.MciSendSmsServiceBulkServiceReference.PolicyException), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="PolicyException", Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
        [System.ServiceModel.FaultContractAttribute(typeof(SharedLibrary.MciSendSmsServiceBulkServiceReference.ServiceException), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="ServiceException", Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleSmsResponse1 scheduleSms(SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/scheduleSmsRequ" +
            "est", ReplyAction="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/scheduleSmsResp" +
            "onse")]
        System.Threading.Tasks.Task<SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleSmsResponse1> scheduleSmsAsync(SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleSmsRequest request);
        
        // CODEGEN: Generating message contract since the operation scheduleBinarySms is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/scheduleBinaryS" +
            "msRequest", ReplyAction="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/scheduleBinaryS" +
            "msResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SharedLibrary.MciSendSmsServiceBulkServiceReference.PolicyException), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="PolicyException", Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
        [System.ServiceModel.FaultContractAttribute(typeof(SharedLibrary.MciSendSmsServiceBulkServiceReference.ServiceException), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="ServiceException", Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleBinarySmsResponse1 scheduleBinarySms(SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleBinarySmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/scheduleBinaryS" +
            "msRequest", ReplyAction="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/scheduleBinaryS" +
            "msResponse")]
        System.Threading.Tasks.Task<SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleBinarySmsResponse1> scheduleBinarySmsAsync(SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleBinarySmsRequest request);
        
        // CODEGEN: Generating message contract since the operation cancelScheduledSms is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/cancelScheduled" +
            "SmsRequest", ReplyAction="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/cancelScheduled" +
            "SmsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SharedLibrary.MciSendSmsServiceBulkServiceReference.PolicyException), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="PolicyException", Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
        [System.ServiceModel.FaultContractAttribute(typeof(SharedLibrary.MciSendSmsServiceBulkServiceReference.ServiceException), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="ServiceException", Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SharedLibrary.MciSendSmsServiceBulkServiceReference.cancelScheduledSmsResponse1 cancelScheduledSms(SharedLibrary.MciSendSmsServiceBulkServiceReference.cancelScheduledSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/cancelScheduled" +
            "SmsRequest", ReplyAction="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/cancelScheduled" +
            "SmsResponse")]
        System.Threading.Tasks.Task<SharedLibrary.MciSendSmsServiceBulkServiceReference.cancelScheduledSmsResponse1> cancelScheduledSmsAsync(SharedLibrary.MciSendSmsServiceBulkServiceReference.cancelScheduledSmsRequest request);
        
        // CODEGEN: Generating message contract since the operation getScheduledSmsStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/getScheduledSms" +
            "StatusRequest", ReplyAction="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/getScheduledSms" +
            "StatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SharedLibrary.MciSendSmsServiceBulkServiceReference.PolicyException), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="PolicyException", Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
        [System.ServiceModel.FaultContractAttribute(typeof(SharedLibrary.MciSendSmsServiceBulkServiceReference.ServiceException), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="ServiceException", Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SharedLibrary.MciSendSmsServiceBulkServiceReference.getScheduledSmsStatusResponse1 getScheduledSmsStatus(SharedLibrary.MciSendSmsServiceBulkServiceReference.getScheduledSmsStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/getScheduledSms" +
            "StatusRequest", ReplyAction="http://www.csapi.org/wsdl/parlayx/sms/send/v4_0/interface/SendSms/getScheduledSms" +
            "StatusResponse")]
        System.Threading.Tasks.Task<SharedLibrary.MciSendSmsServiceBulkServiceReference.getScheduledSmsStatusResponse1> getScheduledSmsStatusAsync(SharedLibrary.MciSendSmsServiceBulkServiceReference.getScheduledSmsStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/send/v4_0/local", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("sendmessage", IsNullable=false)]
        public SharedLibrary.MciSendSmsServiceBulkServiceReference.sendMessage[] sendSms;
        
        public sendSmsRequest() {
        }
        
        public sendSmsRequest(SharedLibrary.MciSendSmsServiceBulkServiceReference.sendMessage[] sendSms) {
            this.sendSms = sendSms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSmsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/send/v4_0/local", Order=0)]
        public SharedLibrary.MciSendSmsServiceBulkServiceReference.sendSmsResponse sendSmsResponse;
        
        public sendSmsResponse1() {
        }
        
        public sendSmsResponse1(SharedLibrary.MciSendSmsServiceBulkServiceReference.sendSmsResponse sendSmsResponse) {
            this.sendSmsResponse = sendSmsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
    public partial class sendBinaryMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] addressesField;
        
        private string senderNameField;
        
        private ChargingInformation chargingField;
        
        private string messageField;
        
        private SimpleReference receiptRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("addresses", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=0)]
        public string[] addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
                this.RaisePropertyChanged("addresses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string senderName {
            get {
                return this.senderNameField;
            }
            set {
                this.senderNameField = value;
                this.RaisePropertyChanged("senderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ChargingInformation charging {
            get {
                return this.chargingField;
            }
            set {
                this.chargingField = value;
                this.RaisePropertyChanged("charging");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public SimpleReference receiptRequest {
            get {
                return this.receiptRequestField;
            }
            set {
                this.receiptRequestField = value;
                this.RaisePropertyChanged("receiptRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/send/v4_0/local")]
    public partial class sendBinarySmsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendBinarySmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/send/v4_0/local", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("sendbinarymessage", IsNullable=false)]
        public SharedLibrary.MciSendSmsServiceBulkServiceReference.sendBinaryMessage[] sendBinarySms;
        
        public sendBinarySmsRequest() {
        }
        
        public sendBinarySmsRequest(SharedLibrary.MciSendSmsServiceBulkServiceReference.sendBinaryMessage[] sendBinarySms) {
            this.sendBinarySms = sendBinarySms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendBinarySmsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/send/v4_0/local", Order=0)]
        public SharedLibrary.MciSendSmsServiceBulkServiceReference.sendBinarySmsResponse sendBinarySmsResponse;
        
        public sendBinarySmsResponse1() {
        }
        
        public sendBinarySmsResponse1(SharedLibrary.MciSendSmsServiceBulkServiceReference.sendBinarySmsResponse sendBinarySmsResponse) {
            this.sendBinarySmsResponse = sendBinarySmsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/send/v4_0/local")]
    public partial class getSmsDeliveryStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string requestIdentifier {
            get {
                return this.requestIdentifierField;
            }
            set {
                this.requestIdentifierField = value;
                this.RaisePropertyChanged("requestIdentifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/v4_0")]
    public partial class DeliveryInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addressField;
        
        private DeliveryStatus deliveryStatusField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=0)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DeliveryStatus deliveryStatus {
            get {
                return this.deliveryStatusField;
            }
            set {
                this.deliveryStatusField = value;
                this.RaisePropertyChanged("deliveryStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/v4_0")]
    public enum DeliveryStatus {
        
        /// <remarks/>
        DeliveredToNetwork,
        
        /// <remarks/>
        DeliveryUncertain,
        
        /// <remarks/>
        DeliveryImpossible,
        
        /// <remarks/>
        MessageWaiting,
        
        /// <remarks/>
        DeliveredToTerminal,
        
        /// <remarks/>
        DeliveryNotificationNotSupported,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSmsDeliveryStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/send/v4_0/local", Order=0)]
        public SharedLibrary.MciSendSmsServiceBulkServiceReference.getSmsDeliveryStatus getSmsDeliveryStatus;
        
        public getSmsDeliveryStatusRequest() {
        }
        
        public getSmsDeliveryStatusRequest(SharedLibrary.MciSendSmsServiceBulkServiceReference.getSmsDeliveryStatus getSmsDeliveryStatus) {
            this.getSmsDeliveryStatus = getSmsDeliveryStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSmsDeliveryStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSmsDeliveryStatusResponse", Namespace="http://www.csapi.org/schema/parlayx/sms/send/v4_0/local", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("result", IsNullable=false)]
        public SharedLibrary.MciSendSmsServiceBulkServiceReference.DeliveryInformation[] getSmsDeliveryStatusResponse1;
        
        public getSmsDeliveryStatusResponse() {
        }
        
        public getSmsDeliveryStatusResponse(SharedLibrary.MciSendSmsServiceBulkServiceReference.DeliveryInformation[] getSmsDeliveryStatusResponse1) {
            this.getSmsDeliveryStatusResponse1 = getSmsDeliveryStatusResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
    public partial class scheduleMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] addressesField;
        
        private string senderNameField;
        
        private ChargingInformation chargingField;
        
        private string messageField;
        
        private System.DateTime startTimeField;
        
        private System.DateTime stopTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("addresses", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=0)]
        public string[] addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
                this.RaisePropertyChanged("addresses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string senderName {
            get {
                return this.senderNameField;
            }
            set {
                this.senderNameField = value;
                this.RaisePropertyChanged("senderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ChargingInformation charging {
            get {
                return this.chargingField;
            }
            set {
                this.chargingField = value;
                this.RaisePropertyChanged("charging");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime startTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
                this.RaisePropertyChanged("startTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime stopTime {
            get {
                return this.stopTimeField;
            }
            set {
                this.stopTimeField = value;
                this.RaisePropertyChanged("stopTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/send/v4_0/local")]
    public partial class scheduleSmsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class scheduleSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/send/v4_0/local", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleMessage[] scheduleSms;
        
        public scheduleSmsRequest() {
        }
        
        public scheduleSmsRequest(SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleMessage[] scheduleSms) {
            this.scheduleSms = scheduleSms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class scheduleSmsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/send/v4_0/local", Order=0)]
        public SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleSmsResponse scheduleSmsResponse;
        
        public scheduleSmsResponse1() {
        }
        
        public scheduleSmsResponse1(SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleSmsResponse scheduleSmsResponse) {
            this.scheduleSmsResponse = scheduleSmsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/common/v4_0")]
    public partial class scheduleBinaryMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] addressesField;
        
        private string senderNameField;
        
        private ChargingInformation chargingField;
        
        private string messageField;
        
        private System.DateTime startTimeField;
        
        private System.DateTime stopTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("addresses", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=0)]
        public string[] addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
                this.RaisePropertyChanged("addresses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string senderName {
            get {
                return this.senderNameField;
            }
            set {
                this.senderNameField = value;
                this.RaisePropertyChanged("senderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ChargingInformation charging {
            get {
                return this.chargingField;
            }
            set {
                this.chargingField = value;
                this.RaisePropertyChanged("charging");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime startTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
                this.RaisePropertyChanged("startTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime stopTime {
            get {
                return this.stopTimeField;
            }
            set {
                this.stopTimeField = value;
                this.RaisePropertyChanged("stopTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/send/v4_0/local")]
    public partial class scheduleBinarySmsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class scheduleBinarySmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/send/v4_0/local", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("schedulebinarymessage", IsNullable=false)]
        public SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleBinaryMessage[] scheduleBinarySms;
        
        public scheduleBinarySmsRequest() {
        }
        
        public scheduleBinarySmsRequest(SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleBinaryMessage[] scheduleBinarySms) {
            this.scheduleBinarySms = scheduleBinarySms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class scheduleBinarySmsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/send/v4_0/local", Order=0)]
        public SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleBinarySmsResponse scheduleBinarySmsResponse;
        
        public scheduleBinarySmsResponse1() {
        }
        
        public scheduleBinarySmsResponse1(SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleBinarySmsResponse scheduleBinarySmsResponse) {
            this.scheduleBinarySmsResponse = scheduleBinarySmsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/send/v4_0/local")]
    public partial class cancelScheduledSms : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string requestIdentifier {
            get {
                return this.requestIdentifierField;
            }
            set {
                this.requestIdentifierField = value;
                this.RaisePropertyChanged("requestIdentifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/send/v4_0/local")]
    public partial class cancelScheduledSmsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelScheduledSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/send/v4_0/local", Order=0)]
        public SharedLibrary.MciSendSmsServiceBulkServiceReference.cancelScheduledSms cancelScheduledSms;
        
        public cancelScheduledSmsRequest() {
        }
        
        public cancelScheduledSmsRequest(SharedLibrary.MciSendSmsServiceBulkServiceReference.cancelScheduledSms cancelScheduledSms) {
            this.cancelScheduledSms = cancelScheduledSms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelScheduledSmsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/send/v4_0/local", Order=0)]
        public SharedLibrary.MciSendSmsServiceBulkServiceReference.cancelScheduledSmsResponse cancelScheduledSmsResponse;
        
        public cancelScheduledSmsResponse1() {
        }
        
        public cancelScheduledSmsResponse1(SharedLibrary.MciSendSmsServiceBulkServiceReference.cancelScheduledSmsResponse cancelScheduledSmsResponse) {
            this.cancelScheduledSmsResponse = cancelScheduledSmsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/send/v4_0/local")]
    public partial class getScheduledSmsStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string requestIdentifier {
            get {
                return this.requestIdentifierField;
            }
            set {
                this.requestIdentifierField = value;
                this.RaisePropertyChanged("requestIdentifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/send/v4_0/local")]
    public partial class getScheduledSmsStatusResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ScheduledDeliveryInformation resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ScheduledDeliveryInformation result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/v4_0")]
    public partial class ScheduledDeliveryInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ScheduledDeliveryStatus deliveryStatusField;
        
        private int numberOfMessagesSentField;
        
        private bool numberOfMessagesSentFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ScheduledDeliveryStatus deliveryStatus {
            get {
                return this.deliveryStatusField;
            }
            set {
                this.deliveryStatusField = value;
                this.RaisePropertyChanged("deliveryStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int numberOfMessagesSent {
            get {
                return this.numberOfMessagesSentField;
            }
            set {
                this.numberOfMessagesSentField = value;
                this.RaisePropertyChanged("numberOfMessagesSent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numberOfMessagesSentSpecified {
            get {
                return this.numberOfMessagesSentFieldSpecified;
            }
            set {
                this.numberOfMessagesSentFieldSpecified = value;
                this.RaisePropertyChanged("numberOfMessagesSentSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/v4_0")]
    public enum ScheduledDeliveryStatus {
        
        /// <remarks/>
        Scheduled,
        
        /// <remarks/>
        NotSent,
        
        /// <remarks/>
        Sent,
        
        /// <remarks/>
        Cancelled,
        
        /// <remarks/>
        PartiallySent,
        
        /// <remarks/>
        StatusUnavailable,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getScheduledSmsStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/send/v4_0/local", Order=0)]
        public SharedLibrary.MciSendSmsServiceBulkServiceReference.getScheduledSmsStatus getScheduledSmsStatus;
        
        public getScheduledSmsStatusRequest() {
        }
        
        public getScheduledSmsStatusRequest(SharedLibrary.MciSendSmsServiceBulkServiceReference.getScheduledSmsStatus getScheduledSmsStatus) {
            this.getScheduledSmsStatus = getScheduledSmsStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getScheduledSmsStatusResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/send/v4_0/local", Order=0)]
        public SharedLibrary.MciSendSmsServiceBulkServiceReference.getScheduledSmsStatusResponse getScheduledSmsStatusResponse;
        
        public getScheduledSmsStatusResponse1() {
        }
        
        public getScheduledSmsStatusResponse1(SharedLibrary.MciSendSmsServiceBulkServiceReference.getScheduledSmsStatusResponse getScheduledSmsStatusResponse) {
            this.getScheduledSmsStatusResponse = getScheduledSmsStatusResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendSmsChannel : SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendSmsClient : System.ServiceModel.ClientBase<SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms>, SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms {
        
        public SendSmsClient() {
        }
        
        public SendSmsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendSmsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSmsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSmsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharedLibrary.MciSendSmsServiceBulkServiceReference.sendSmsResponse1 SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms.sendSms(SharedLibrary.MciSendSmsServiceBulkServiceReference.sendSmsRequest request) {
            return base.Channel.sendSms(request);
        }
        
        public SharedLibrary.MciSendSmsServiceBulkServiceReference.sendSmsResponse sendSms(SharedLibrary.MciSendSmsServiceBulkServiceReference.sendMessage[] sendSms1) {
            SharedLibrary.MciSendSmsServiceBulkServiceReference.sendSmsRequest inValue = new SharedLibrary.MciSendSmsServiceBulkServiceReference.sendSmsRequest();
            inValue.sendSms = sendSms1;
            SharedLibrary.MciSendSmsServiceBulkServiceReference.sendSmsResponse1 retVal = ((SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms)(this)).sendSms(inValue);
            return retVal.sendSmsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharedLibrary.MciSendSmsServiceBulkServiceReference.sendSmsResponse1> SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms.sendSmsAsync(SharedLibrary.MciSendSmsServiceBulkServiceReference.sendSmsRequest request) {
            return base.Channel.sendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharedLibrary.MciSendSmsServiceBulkServiceReference.sendSmsResponse1> sendSmsAsync(SharedLibrary.MciSendSmsServiceBulkServiceReference.sendMessage[] sendSms) {
            SharedLibrary.MciSendSmsServiceBulkServiceReference.sendSmsRequest inValue = new SharedLibrary.MciSendSmsServiceBulkServiceReference.sendSmsRequest();
            inValue.sendSms = sendSms;
            return ((SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms)(this)).sendSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharedLibrary.MciSendSmsServiceBulkServiceReference.sendBinarySmsResponse1 SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms.sendBinarySms(SharedLibrary.MciSendSmsServiceBulkServiceReference.sendBinarySmsRequest request) {
            return base.Channel.sendBinarySms(request);
        }
        
        public SharedLibrary.MciSendSmsServiceBulkServiceReference.sendBinarySmsResponse sendBinarySms(SharedLibrary.MciSendSmsServiceBulkServiceReference.sendBinaryMessage[] sendBinarySms1) {
            SharedLibrary.MciSendSmsServiceBulkServiceReference.sendBinarySmsRequest inValue = new SharedLibrary.MciSendSmsServiceBulkServiceReference.sendBinarySmsRequest();
            inValue.sendBinarySms = sendBinarySms1;
            SharedLibrary.MciSendSmsServiceBulkServiceReference.sendBinarySmsResponse1 retVal = ((SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms)(this)).sendBinarySms(inValue);
            return retVal.sendBinarySmsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharedLibrary.MciSendSmsServiceBulkServiceReference.sendBinarySmsResponse1> SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms.sendBinarySmsAsync(SharedLibrary.MciSendSmsServiceBulkServiceReference.sendBinarySmsRequest request) {
            return base.Channel.sendBinarySmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharedLibrary.MciSendSmsServiceBulkServiceReference.sendBinarySmsResponse1> sendBinarySmsAsync(SharedLibrary.MciSendSmsServiceBulkServiceReference.sendBinaryMessage[] sendBinarySms) {
            SharedLibrary.MciSendSmsServiceBulkServiceReference.sendBinarySmsRequest inValue = new SharedLibrary.MciSendSmsServiceBulkServiceReference.sendBinarySmsRequest();
            inValue.sendBinarySms = sendBinarySms;
            return ((SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms)(this)).sendBinarySmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharedLibrary.MciSendSmsServiceBulkServiceReference.getSmsDeliveryStatusResponse SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms.getSmsDeliveryStatus(SharedLibrary.MciSendSmsServiceBulkServiceReference.getSmsDeliveryStatusRequest request) {
            return base.Channel.getSmsDeliveryStatus(request);
        }
        
        public SharedLibrary.MciSendSmsServiceBulkServiceReference.DeliveryInformation[] getSmsDeliveryStatus(SharedLibrary.MciSendSmsServiceBulkServiceReference.getSmsDeliveryStatus getSmsDeliveryStatus1) {
            SharedLibrary.MciSendSmsServiceBulkServiceReference.getSmsDeliveryStatusRequest inValue = new SharedLibrary.MciSendSmsServiceBulkServiceReference.getSmsDeliveryStatusRequest();
            inValue.getSmsDeliveryStatus = getSmsDeliveryStatus1;
            SharedLibrary.MciSendSmsServiceBulkServiceReference.getSmsDeliveryStatusResponse retVal = ((SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms)(this)).getSmsDeliveryStatus(inValue);
            return retVal.getSmsDeliveryStatusResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharedLibrary.MciSendSmsServiceBulkServiceReference.getSmsDeliveryStatusResponse> SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms.getSmsDeliveryStatusAsync(SharedLibrary.MciSendSmsServiceBulkServiceReference.getSmsDeliveryStatusRequest request) {
            return base.Channel.getSmsDeliveryStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharedLibrary.MciSendSmsServiceBulkServiceReference.getSmsDeliveryStatusResponse> getSmsDeliveryStatusAsync(SharedLibrary.MciSendSmsServiceBulkServiceReference.getSmsDeliveryStatus getSmsDeliveryStatus) {
            SharedLibrary.MciSendSmsServiceBulkServiceReference.getSmsDeliveryStatusRequest inValue = new SharedLibrary.MciSendSmsServiceBulkServiceReference.getSmsDeliveryStatusRequest();
            inValue.getSmsDeliveryStatus = getSmsDeliveryStatus;
            return ((SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms)(this)).getSmsDeliveryStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleSmsResponse1 SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms.scheduleSms(SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleSmsRequest request) {
            return base.Channel.scheduleSms(request);
        }
        
        public SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleSmsResponse scheduleSms(SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleMessage[] scheduleSms1) {
            SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleSmsRequest inValue = new SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleSmsRequest();
            inValue.scheduleSms = scheduleSms1;
            SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleSmsResponse1 retVal = ((SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms)(this)).scheduleSms(inValue);
            return retVal.scheduleSmsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleSmsResponse1> SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms.scheduleSmsAsync(SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleSmsRequest request) {
            return base.Channel.scheduleSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleSmsResponse1> scheduleSmsAsync(SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleMessage[] scheduleSms) {
            SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleSmsRequest inValue = new SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleSmsRequest();
            inValue.scheduleSms = scheduleSms;
            return ((SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms)(this)).scheduleSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleBinarySmsResponse1 SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms.scheduleBinarySms(SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleBinarySmsRequest request) {
            return base.Channel.scheduleBinarySms(request);
        }
        
        public SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleBinarySmsResponse scheduleBinarySms(SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleBinaryMessage[] scheduleBinarySms1) {
            SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleBinarySmsRequest inValue = new SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleBinarySmsRequest();
            inValue.scheduleBinarySms = scheduleBinarySms1;
            SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleBinarySmsResponse1 retVal = ((SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms)(this)).scheduleBinarySms(inValue);
            return retVal.scheduleBinarySmsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleBinarySmsResponse1> SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms.scheduleBinarySmsAsync(SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleBinarySmsRequest request) {
            return base.Channel.scheduleBinarySmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleBinarySmsResponse1> scheduleBinarySmsAsync(SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleBinaryMessage[] scheduleBinarySms) {
            SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleBinarySmsRequest inValue = new SharedLibrary.MciSendSmsServiceBulkServiceReference.scheduleBinarySmsRequest();
            inValue.scheduleBinarySms = scheduleBinarySms;
            return ((SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms)(this)).scheduleBinarySmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharedLibrary.MciSendSmsServiceBulkServiceReference.cancelScheduledSmsResponse1 SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms.cancelScheduledSms(SharedLibrary.MciSendSmsServiceBulkServiceReference.cancelScheduledSmsRequest request) {
            return base.Channel.cancelScheduledSms(request);
        }
        
        public SharedLibrary.MciSendSmsServiceBulkServiceReference.cancelScheduledSmsResponse cancelScheduledSms(SharedLibrary.MciSendSmsServiceBulkServiceReference.cancelScheduledSms cancelScheduledSms1) {
            SharedLibrary.MciSendSmsServiceBulkServiceReference.cancelScheduledSmsRequest inValue = new SharedLibrary.MciSendSmsServiceBulkServiceReference.cancelScheduledSmsRequest();
            inValue.cancelScheduledSms = cancelScheduledSms1;
            SharedLibrary.MciSendSmsServiceBulkServiceReference.cancelScheduledSmsResponse1 retVal = ((SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms)(this)).cancelScheduledSms(inValue);
            return retVal.cancelScheduledSmsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharedLibrary.MciSendSmsServiceBulkServiceReference.cancelScheduledSmsResponse1> SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms.cancelScheduledSmsAsync(SharedLibrary.MciSendSmsServiceBulkServiceReference.cancelScheduledSmsRequest request) {
            return base.Channel.cancelScheduledSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharedLibrary.MciSendSmsServiceBulkServiceReference.cancelScheduledSmsResponse1> cancelScheduledSmsAsync(SharedLibrary.MciSendSmsServiceBulkServiceReference.cancelScheduledSms cancelScheduledSms) {
            SharedLibrary.MciSendSmsServiceBulkServiceReference.cancelScheduledSmsRequest inValue = new SharedLibrary.MciSendSmsServiceBulkServiceReference.cancelScheduledSmsRequest();
            inValue.cancelScheduledSms = cancelScheduledSms;
            return ((SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms)(this)).cancelScheduledSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharedLibrary.MciSendSmsServiceBulkServiceReference.getScheduledSmsStatusResponse1 SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms.getScheduledSmsStatus(SharedLibrary.MciSendSmsServiceBulkServiceReference.getScheduledSmsStatusRequest request) {
            return base.Channel.getScheduledSmsStatus(request);
        }
        
        public SharedLibrary.MciSendSmsServiceBulkServiceReference.getScheduledSmsStatusResponse getScheduledSmsStatus(SharedLibrary.MciSendSmsServiceBulkServiceReference.getScheduledSmsStatus getScheduledSmsStatus1) {
            SharedLibrary.MciSendSmsServiceBulkServiceReference.getScheduledSmsStatusRequest inValue = new SharedLibrary.MciSendSmsServiceBulkServiceReference.getScheduledSmsStatusRequest();
            inValue.getScheduledSmsStatus = getScheduledSmsStatus1;
            SharedLibrary.MciSendSmsServiceBulkServiceReference.getScheduledSmsStatusResponse1 retVal = ((SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms)(this)).getScheduledSmsStatus(inValue);
            return retVal.getScheduledSmsStatusResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharedLibrary.MciSendSmsServiceBulkServiceReference.getScheduledSmsStatusResponse1> SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms.getScheduledSmsStatusAsync(SharedLibrary.MciSendSmsServiceBulkServiceReference.getScheduledSmsStatusRequest request) {
            return base.Channel.getScheduledSmsStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharedLibrary.MciSendSmsServiceBulkServiceReference.getScheduledSmsStatusResponse1> getScheduledSmsStatusAsync(SharedLibrary.MciSendSmsServiceBulkServiceReference.getScheduledSmsStatus getScheduledSmsStatus) {
            SharedLibrary.MciSendSmsServiceBulkServiceReference.getScheduledSmsStatusRequest inValue = new SharedLibrary.MciSendSmsServiceBulkServiceReference.getScheduledSmsStatusRequest();
            inValue.getScheduledSmsStatus = getScheduledSmsStatus;
            return ((SharedLibrary.MciSendSmsServiceBulkServiceReference.SendSms)(this)).getScheduledSmsStatusAsync(inValue);
        }
    }
}
