//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedLibrary.HubServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HubServiceReference.SmsSoap")]
    public interface SmsSoap {
        
        // CODEGEN: Generating message contract since element name requestData from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmsRequest", ReplyAction="*")]
        SharedLibrary.HubServiceReference.XmsRequestResponse XmsRequest(SharedLibrary.HubServiceReference.XmsRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmsRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<SharedLibrary.HubServiceReference.XmsRequestResponse> XmsRequestAsync(SharedLibrary.HubServiceReference.XmsRequestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmsRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmsRequest", Namespace="http://tempuri.org/", Order=0)]
        public SharedLibrary.HubServiceReference.XmsRequestRequestBody Body;
        
        public XmsRequestRequest() {
        }
        
        public XmsRequestRequest(SharedLibrary.HubServiceReference.XmsRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XmsRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestData;
        
        public XmsRequestRequestBody() {
        }
        
        public XmsRequestRequestBody(string requestData) {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmsRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmsRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public SharedLibrary.HubServiceReference.XmsRequestResponseBody Body;
        
        public XmsRequestResponse() {
        }
        
        public XmsRequestResponse(SharedLibrary.HubServiceReference.XmsRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XmsRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object XmsRequestResult;
        
        public XmsRequestResponseBody() {
        }
        
        public XmsRequestResponseBody(object XmsRequestResult) {
            this.XmsRequestResult = XmsRequestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmsSoapChannel : SharedLibrary.HubServiceReference.SmsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsSoapClient : System.ServiceModel.ClientBase<SharedLibrary.HubServiceReference.SmsSoap>, SharedLibrary.HubServiceReference.SmsSoap {
        
        public SmsSoapClient() {
        }
        
        public SmsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SharedLibrary.HubServiceReference.XmsRequestResponse SharedLibrary.HubServiceReference.SmsSoap.XmsRequest(SharedLibrary.HubServiceReference.XmsRequestRequest request) {
            return base.Channel.XmsRequest(request);
        }
        
        public object XmsRequest(string requestData) {
            SharedLibrary.HubServiceReference.XmsRequestRequest inValue = new SharedLibrary.HubServiceReference.XmsRequestRequest();
            inValue.Body = new SharedLibrary.HubServiceReference.XmsRequestRequestBody();
            inValue.Body.requestData = requestData;
            SharedLibrary.HubServiceReference.XmsRequestResponse retVal = ((SharedLibrary.HubServiceReference.SmsSoap)(this)).XmsRequest(inValue);
            return retVal.Body.XmsRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SharedLibrary.HubServiceReference.XmsRequestResponse> SharedLibrary.HubServiceReference.SmsSoap.XmsRequestAsync(SharedLibrary.HubServiceReference.XmsRequestRequest request) {
            return base.Channel.XmsRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<SharedLibrary.HubServiceReference.XmsRequestResponse> XmsRequestAsync(string requestData) {
            SharedLibrary.HubServiceReference.XmsRequestRequest inValue = new SharedLibrary.HubServiceReference.XmsRequestRequest();
            inValue.Body = new SharedLibrary.HubServiceReference.XmsRequestRequestBody();
            inValue.Body.requestData = requestData;
            return ((SharedLibrary.HubServiceReference.SmsSoap)(this)).XmsRequestAsync(inValue);
        }
    }
}
