//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvvalPod500Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutochargeTimeTable
    {
        public long Id { get; set; }
        public int Tag { get; set; }
        public string SendTime { get; set; }
    }
}
