//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamlyLibrary.Models
{
    using System;
    
    public partial class SinglechargeLiveStatuses_Result1
    {
        public Nullable<int> TotalTries { get; set; }
        public string Description { get; set; }
        public Nullable<int> DistinctNumbersTried { get; set; }
        public Nullable<int> Income { get; set; }
    }
}
