//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsersRolesServiceAccess
    {
        public int id { get; set; }
        public string userId { get; set; }
        public string roleId { get; set; }
        public Nullable<long> serviceId { get; set; }
        public Nullable<long> aggregatorId { get; set; }
    }
}
