//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkList
    {
        public long Id { get; set; }
        public string MobileNumbersList { get; set; }
        public string Message { get; set; }
        public string ServiceCode { get; set; }
        public bool IsDone { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string PersianDateAdded { get; set; }
    }
}
