//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignsMobileNumber
    {
        public long Id { get; set; }
        public Nullable<int> campaignId { get; set; }
        public string campaignType { get; set; }
        public string mobileNumber { get; set; }
        public Nullable<System.DateTime> receivedTime { get; set; }
        public string keyword { get; set; }
        public Nullable<bool> paid { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
