//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobinOneFtp
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> regDate { get; set; }
        public string serviceCode { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string service_name { get; set; }
        public string event_type { get; set; }
        public string requestedChannel { get; set; }
        public string download_channel { get; set; }
        public Nullable<decimal> eup { get; set; }
        public string action_type { get; set; }
        public string subscriber_type { get; set; }
        public string shortcode { get; set; }
        public Nullable<int> downloads { get; set; }
        public Nullable<int> revenue { get; set; }
    }
}
