//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealtimeStatisticsFor2GServices
    {
        public long Id { get; set; }
        public System.DateTime Date { get; set; }
        public string PersianDate { get; set; }
        public long ServiceId { get; set; }
        public string ServiceName { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public Nullable<int> PrepaidSubscriptions { get; set; }
        public Nullable<int> PostPaidSubscriptions { get; set; }
        public Nullable<int> PrepaidUnsubscriptions { get; set; }
        public Nullable<int> PostPaidUnsubscriptions { get; set; }
    }
}
