//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealtimeStatisticsFor3GServices
    {
        public long Id { get; set; }
        public System.DateTime Date { get; set; }
        public string PersianDate { get; set; }
        public long ServiceId { get; set; }
        public Nullable<int> TotalSubscriptions { get; set; }
        public Nullable<int> TotalUnsubscriptions { get; set; }
        public Nullable<int> TodayGenuineSubscriptions { get; set; }
        public Nullable<int> ActivationRateByMinute { get; set; }
        public Nullable<int> ActivationRateByHour { get; set; }
        public Nullable<int> DeactivationRateByMinute { get; set; }
        public Nullable<int> DeactivationRateByHour { get; set; }
        public Nullable<int> GeniuneActivationRateByMinute { get; set; }
        public Nullable<int> GeniueActivationRateByHour { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string ServiceName { get; set; }
        public Nullable<int> TotalUnsubcribriptions { get; set; }
        public Nullable<int> AllDeactivedSubscribers { get; set; }
        public Nullable<int> ActiveSubscribersFromHistory { get; set; }
        public Nullable<int> ActiveSubscribersFromHistoryUnique { get; set; }
        public Nullable<int> DeactivedSubscribersFromHistory { get; set; }
        public Nullable<int> DeactivedSubscribersFromHistoryUnqiue { get; set; }
    }
}
