//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscribersHistory
    {
        public long Id { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<long> ServiceId { get; set; }
        public string ShortCode { get; set; }
        public string AggregatorServiceId { get; set; }
        public string ServiceName { get; set; }
        public Nullable<int> ServiceStatusForSubscriber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> WhoChangedSubscriberStatus { get; set; }
        public string InvalidContent { get; set; }
        public Nullable<long> AggregatorId { get; set; }
        public string AggregatorName { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string PersianDateTime { get; set; }
        public string SubscriptionKeyword { get; set; }
        public string UnsubscriptionKeyword { get; set; }
    }
}
