//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_chargeLog
    {
        public int id { get; set; }
        public string serviceCode { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
        public Nullable<decimal> sumPrice { get; set; }
        public Nullable<long> sumTries { get; set; }
        public Nullable<long> activeUsers { get; set; }
    }
}
