//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_servicesServicesInfo
    {
        public Nullable<int> userCount { get; set; }
        public Nullable<int> activeUserCount { get; set; }
        public int TodayTillNowChargeAmount { get; set; }
        public long Id { get; set; }
        public string Name { get; set; }
        public string ServiceCode { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string OnKeywords { get; set; }
        public bool IsServiceActive { get; set; }
        public Nullable<bool> Enable2StepSubscription { get; set; }
        public string oldServiceCodes { get; set; }
        public string referralUrl { get; set; }
        public Nullable<long> ServiceInfoId { get; set; }
        public Nullable<long> AggregatorId { get; set; }
        public string ShortCode { get; set; }
        public string AggregatorServiceId { get; set; }
        public string OperatorServiceId { get; set; }
        public string ServiceName { get; set; }
        public string databaseName { get; set; }
        public Nullable<int> chargePrice { get; set; }
        public string aggregatorName { get; set; }
    }
}
