//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BimeIranLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DamageReport
    {
        public long Id { get; set; }
        public long InsuranceId { get; set; }
        public System.DateTime DateDamageReported { get; set; }
        public string PersianDateDamageReported { get; set; }
        public bool IsSendedToInsuranceCompany { get; set; }
        public Nullable<bool> IsDeliveryReceivedFromInsuranceCompany { get; set; }
    
        public virtual InsuranceInfo InsuranceInfo { get; set; }
    }
}
