//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BimeIranLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceInfo
    {
        public long Id { get; set; }
        public string MobileNumber { get; set; }
        public string PassportNo { get; set; }
        public bool IsApproved { get; set; }
        public string ConfirmationCode { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string PersianDateCreated { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public string PersianDateApproved { get; set; }
        public string InsuranceNo { get; set; }
        public string SocialNumber { get; set; }
        public string ZipCode { get; set; }
    }
}
