//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakavarLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinglechargeLiveStatu
    {
        public long Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string PersianDateCreated { get; set; }
        public string SinglechargeStatuses { get; set; }
        public int NumberOfSinglechargesTried { get; set; }
    }
}
