//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.PardisImiServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="PardisAvvalKish.ir", ConfigurationName="PardisImiServiceReference.MTSoap")]
    public interface MTSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="PardisAvvalKish.ir/SendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SendSMS(string SPID, Portal.PardisImiServiceReference.SMS[] BatchSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="PardisAvvalKish.ir/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> SendSMSAsync(string SPID, Portal.PardisImiServiceReference.SMS[] BatchSMS);
        
        // CODEGEN: Parameter 'SendSMS2Result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="PardisAvvalKish.ir/SendSMS2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Portal.PardisImiServiceReference.SendSMS2Response SendSMS2(Portal.PardisImiServiceReference.SendSMS2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PardisAvvalKish.ir/SendSMS2", ReplyAction="*")]
        System.Threading.Tasks.Task<Portal.PardisImiServiceReference.SendSMS2Response> SendSMS2Async(Portal.PardisImiServiceReference.SendSMS2Request request);
        
        // CODEGEN: Parameter 'SendSMSPlusResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="PardisAvvalKish.ir/SendSMSPlus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Portal.PardisImiServiceReference.SendSMSPlusResponse SendSMSPlus(Portal.PardisImiServiceReference.SendSMSPlusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="PardisAvvalKish.ir/SendSMSPlus", ReplyAction="*")]
        System.Threading.Tasks.Task<Portal.PardisImiServiceReference.SendSMSPlusResponse> SendSMSPlusAsync(Portal.PardisImiServiceReference.SendSMSPlusRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PardisAvvalKish.ir")]
    public partial class SMS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string shortCodeField;
        
        private string addressesField;
        
        private string messageField;
        
        private string chargeCodeField;
        
        private int indexField;
        
        private string subUnsubMoMessageField;
        
        private byte subUnsubTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ShortCode {
            get {
                return this.shortCodeField;
            }
            set {
                this.shortCodeField = value;
                this.RaisePropertyChanged("ShortCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
                this.RaisePropertyChanged("Addresses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ChargeCode {
            get {
                return this.chargeCodeField;
            }
            set {
                this.chargeCodeField = value;
                this.RaisePropertyChanged("ChargeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
                this.RaisePropertyChanged("Index");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SubUnsubMoMessage {
            get {
                return this.subUnsubMoMessageField;
            }
            set {
                this.subUnsubMoMessageField = value;
                this.RaisePropertyChanged("SubUnsubMoMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public byte SubUnsubType {
            get {
                return this.subUnsubTypeField;
            }
            set {
                this.subUnsubTypeField = value;
                this.RaisePropertyChanged("SubUnsubType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMS2", WrapperNamespace="PardisAvvalKish.ir", IsWrapped=true)]
    public partial class SendSMS2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="PardisAvvalKish.ir", Order=0)]
        public string SPID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="PardisAvvalKish.ir", Order=1)]
        public Portal.PardisImiServiceReference.SMS[] BatchSMS;
        
        public SendSMS2Request() {
        }
        
        public SendSMS2Request(string SPID, Portal.PardisImiServiceReference.SMS[] BatchSMS) {
            this.SPID = SPID;
            this.BatchSMS = BatchSMS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMS2Response", WrapperNamespace="PardisAvvalKish.ir", IsWrapped=true)]
    public partial class SendSMS2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="PardisAvvalKish.ir", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] SendSMS2Result;
        
        public SendSMS2Response() {
        }
        
        public SendSMS2Response(string[][] SendSMS2Result) {
            this.SendSMS2Result = SendSMS2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMSPlus", WrapperNamespace="PardisAvvalKish.ir", IsWrapped=true)]
    public partial class SendSMSPlusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="PardisAvvalKish.ir", Order=0)]
        public string SPID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="PardisAvvalKish.ir", Order=1)]
        public Portal.PardisImiServiceReference.SMS[] BatchSMS;
        
        public SendSMSPlusRequest() {
        }
        
        public SendSMSPlusRequest(string SPID, Portal.PardisImiServiceReference.SMS[] BatchSMS) {
            this.SPID = SPID;
            this.BatchSMS = BatchSMS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMSPlusResponse", WrapperNamespace="PardisAvvalKish.ir", IsWrapped=true)]
    public partial class SendSMSPlusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="PardisAvvalKish.ir", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] SendSMSPlusResult;
        
        public SendSMSPlusResponse() {
        }
        
        public SendSMSPlusResponse(string[][] SendSMSPlusResult) {
            this.SendSMSPlusResult = SendSMSPlusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MTSoapChannel : Portal.PardisImiServiceReference.MTSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MTSoapClient : System.ServiceModel.ClientBase<Portal.PardisImiServiceReference.MTSoap>, Portal.PardisImiServiceReference.MTSoap {
        
        public MTSoapClient() {
        }
        
        public MTSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MTSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MTSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MTSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable SendSMS(string SPID, Portal.PardisImiServiceReference.SMS[] BatchSMS) {
            return base.Channel.SendSMS(SPID, BatchSMS);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SendSMSAsync(string SPID, Portal.PardisImiServiceReference.SMS[] BatchSMS) {
            return base.Channel.SendSMSAsync(SPID, BatchSMS);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Portal.PardisImiServiceReference.SendSMS2Response Portal.PardisImiServiceReference.MTSoap.SendSMS2(Portal.PardisImiServiceReference.SendSMS2Request request) {
            return base.Channel.SendSMS2(request);
        }
        
        public string[][] SendSMS2(string SPID, Portal.PardisImiServiceReference.SMS[] BatchSMS) {
            Portal.PardisImiServiceReference.SendSMS2Request inValue = new Portal.PardisImiServiceReference.SendSMS2Request();
            inValue.SPID = SPID;
            inValue.BatchSMS = BatchSMS;
            Portal.PardisImiServiceReference.SendSMS2Response retVal = ((Portal.PardisImiServiceReference.MTSoap)(this)).SendSMS2(inValue);
            return retVal.SendSMS2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Portal.PardisImiServiceReference.SendSMS2Response> Portal.PardisImiServiceReference.MTSoap.SendSMS2Async(Portal.PardisImiServiceReference.SendSMS2Request request) {
            return base.Channel.SendSMS2Async(request);
        }
        
        public System.Threading.Tasks.Task<Portal.PardisImiServiceReference.SendSMS2Response> SendSMS2Async(string SPID, Portal.PardisImiServiceReference.SMS[] BatchSMS) {
            Portal.PardisImiServiceReference.SendSMS2Request inValue = new Portal.PardisImiServiceReference.SendSMS2Request();
            inValue.SPID = SPID;
            inValue.BatchSMS = BatchSMS;
            return ((Portal.PardisImiServiceReference.MTSoap)(this)).SendSMS2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Portal.PardisImiServiceReference.SendSMSPlusResponse Portal.PardisImiServiceReference.MTSoap.SendSMSPlus(Portal.PardisImiServiceReference.SendSMSPlusRequest request) {
            return base.Channel.SendSMSPlus(request);
        }
        
        public string[][] SendSMSPlus(string SPID, Portal.PardisImiServiceReference.SMS[] BatchSMS) {
            Portal.PardisImiServiceReference.SendSMSPlusRequest inValue = new Portal.PardisImiServiceReference.SendSMSPlusRequest();
            inValue.SPID = SPID;
            inValue.BatchSMS = BatchSMS;
            Portal.PardisImiServiceReference.SendSMSPlusResponse retVal = ((Portal.PardisImiServiceReference.MTSoap)(this)).SendSMSPlus(inValue);
            return retVal.SendSMSPlusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Portal.PardisImiServiceReference.SendSMSPlusResponse> Portal.PardisImiServiceReference.MTSoap.SendSMSPlusAsync(Portal.PardisImiServiceReference.SendSMSPlusRequest request) {
            return base.Channel.SendSMSPlusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Portal.PardisImiServiceReference.SendSMSPlusResponse> SendSMSPlusAsync(string SPID, Portal.PardisImiServiceReference.SMS[] BatchSMS) {
            Portal.PardisImiServiceReference.SendSMSPlusRequest inValue = new Portal.PardisImiServiceReference.SendSMSPlusRequest();
            inValue.SPID = SPID;
            inValue.BatchSMS = BatchSMS;
            return ((Portal.PardisImiServiceReference.MTSoap)(this)).SendSMSPlusAsync(inValue);
        }
    }
}
